#!/usr/bin/env node
import { mkdir, writeFile, rm } from "node:fs/promises";
import path from "node:path";

const fixtureRoot = path.resolve(".fixtures", "basic-workspace");
const force = process.argv.includes("--force");

if (force) {
  await rm(fixtureRoot, { recursive: true, force: true });
}

const dirs = [
  "sources/raw",
  "assets",
  "transcripts",
  "timelines",
  "jobs",
  "renders",
  ".claude/skills",
  ".codex/skills",
  ".pi/skills"
];

for (const dir of dirs) {
  await mkdir(path.join(fixtureRoot, dir), { recursive: true });
}

await writeFile(
  path.join(fixtureRoot, "README.md"),
  `# Henshusha basic fixture\n\nThis fixture is generated by \`pnpm dev:fixture\`.\n\nUse it to dogfood generated workspace shape before \`create-henshusha\` is implemented.\n`,
  "utf8"
);

await writeFile(
  path.join(fixtureRoot, "henshusha.config.json"),
  JSON.stringify(
    {
      sourcesDir: "sources/raw",
      transcriptsDir: "transcripts",
      timelinesDir: "timelines",
      rendersDir: "renders",
      defaultAsrProvider: "mock"
    },
    null,
    2
  ) + "\n",
  "utf8"
);

await writeFile(
  path.join(fixtureRoot, "timelines", "sample.timeline.json"),
  JSON.stringify(
    {
      version: "0.1",
      source: {
        path: "sources/raw/sample.mp4",
        audio: "assets/sample.wav"
      },
      transcript: {
        language: "ja",
        segments: [
          {
            id: "seg_001",
            start: 0,
            end: 2.4,
            text: "これは編集者のサンプルです",
            words: [
              { text: "これは", start: 0, end: 0.5, confidence: 0.99 },
              { text: "編集者", start: 0.5, end: 1.2, confidence: 0.99 },
              { text: "の", start: 1.2, end: 1.35, confidence: 0.99 },
              { text: "サンプルです", start: 1.35, end: 2.4, confidence: 0.99 }
            ]
          }
        ]
      },
      render: {
        variant: {
          aspect: "9:16",
          resolution: "1080x1920",
          safeArea: "short-video"
        },
        artDirection: {
          preset: "clean-bold-captions",
          captionStyle: "karaoke-highlight"
        }
      }
    },
    null,
    2
  ) + "\n",
  "utf8"
);

console.log(`Created fixture at ${fixtureRoot}`);
console.log("Next: open the fixture in Claude Code, Codex, or Pi and dogfood the skills workflow.");
